server:
  port: 8083
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    druid:
      url: jdbc:mysql://106.13.47.59:3306/systemmonitor?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: root
      password: Bluewave1.
      driver-class-name: com.mysql.jdbc.Driver
      #连接池初始化大小最小最大
      initial-size: 2
      min-idle: 2
      max-active: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #验证连接是否可用，使用的SQL语句
      validation-query: SELECT 1
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      #监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: bluewaveadmin
        login-password: bluewaveadmin
        #是否能按重制按键
        reset-enable: true